[[redirects]]
  from = "/realwordassets"
  to = "/realworldassets"
  status = 301

[[redirects]]
  from = "/realwordassets.html"
  to = "/realworldassets"
  status = 301

[[redirects]]
  from = "/stablecoin.html"
  to = "/stablecoins"
  status = 301

[[redirects]]
  from = "/stablecoin"
  to = "/stablecoins"
  status = 301

[[redirects]]
  from = "/web3-cross-chain-bridge-audit.html"
  to = "/crosschainbridge"
  status = 301

[[redirects]]
  from = "/web3-cross-chain-bridge-audit"
  to = "/crosschainbridge"
  status = 301

[[redirects]]
  from = "/web3-defi-protocol-audit.html"
  to = "/dapp-protocol-security"
  status = 301

[[redirects]]
  from = "/web3-defi-protocol-audit"
  to = "/dapp-protocol-security"
  status = 301

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/css/*.v*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*.v*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
